services:
  - type: web
    name: gestion-documentacion
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
